Repository wp-cli/extension-command, pull requests merged in 2019-11, with the labels that each got.

#200 Add second must-use plugin that is added with wp-cli-tests 2.1.6+
  composer.json
  features/plugin.feature
Labels: scope:testing

#196 WP-CLI Themes: Added workaround to equalize folder naming conventions across Win/Mac/Linux
  features/theme.feature
  src/WP_CLI/Fetchers/Theme.php
Labels: bug, command:theme

#201 Add preliminary PHP 7.4 testing
  .travis.yml
Labels: scope:distribution
