Repository wp-cli/extension-command, pull requests merged in 2019-04, with the labels that each got.

#164 Move PHP 5.4 tests from `WP_VERSION` `latest` to `5.1`
  .travis.yml
Labels: scope:distribution

#169 Enhancement: Add PHP 7.3 to Travis CI build matrix
  .travis.yml
Labels: scope:testing

#170 Implement CS checking based on the `WP_CLI_CS` ruleset
  .distignore
  .gitignore
  composer.json
  extension-command.php
  phpcs.xml.dist
  src/Plugin_Command.php
  src/Theme_Command.php
  src/Theme_Mod_Command.php
  src/WP_CLI/CommandWithUpgrade.php
  src/WP_CLI/DestructivePluginUpgrader.php
  src/WP_CLI/DestructiveThemeUpgrader.php
  src/WP_CLI/Fetchers/Plugin.php
  src/WP_CLI/Fetchers/Theme.php
Labels: scope:testing

#167 Add the `--page` parameter to the `theme search` command
  README.md
  src/Theme_Command.php
Labels: bug, command:theme-search

#173 Update README.md file
  README.md
Labels: scope:documentation
