Repository wp-cli/extension-command, pull requests merged in 2020-04, with the labels that each got.

#220 Add Alain Schlesser to composer.json author list
  composer.json
Labels: scope:distribution

#219 Fix Travis CI `sudo` warning
  .travis.yml
Labels: scope:distribution

#222 Missing `--network` parameter for `plugin is-active`
  src/Plugin_Command.php
Labels: command:plugin-is-active

#226 Enforce PHP 7.4 compatibility in Travis CI
  .travis.yml
Labels: scope:testing

#227 Bump Travis CI OS from `trusty` to `xenial`
  .travis.yml
Labels: scope:testing
